import { SharedIncidentMemory } from "@/application/shared-memory/shared-incident-memory";
import { IncidentEntity } from "@/domain/entities/incident";
import { RiskAssessment } from "@/domain/entities/risk-evaluator";
import { SharedMemoryFailureError } from "@/shared/errors/risk-evaluator-service-errors";

export class SharedIncidentMemoryIntegration {
  constructor(private readonly sharedMemory: SharedIncidentMemory) {}

  /**
   * Reads an incident record from the Shared Incident Memory.
   */
  public async readIncident(incidentId: string): Promise<IncidentEntity | null> {
    try {
      return await this.sharedMemory.read(incidentId);
    } catch (error: any) {
      throw new SharedMemoryFailureError(`Failed to read from Shared Incident Memory: ${error.message}`, error);
    }
  }

  /**
   * Appends Risk Evaluator telemetry data to the Shared Incident Memory
   * without overwriting any fields generated by the Data Dispatcher.
   */
  public async appendRiskEvaluatorData(
    incidentId: string,
    assessment: RiskAssessment
  ): Promise<IncidentEntity> {
    try {
      const current = await this.readIncident(incidentId);
      if (!current) {
        throw new SharedMemoryFailureError(`Incident ${incidentId} not found in Shared Memory`);
      }

      // Safeguard: Ensure we merge metadata instead of overwriting dispatcher metadata
      const currentMetadata = current.metadata && typeof current.metadata === "object" ? current.metadata : {};
      
      const riskPayload = {
        assessmentId: assessment.id,
        severity: assessment.severity,
        priority: assessment.priority,
        overallRiskScore: assessment.overallRiskScore,
        confidence: assessment.confidence,
        reasoning: assessment.reasoning,
        isProtocolZeroTriggered: assessment.isProtocolZeroTriggered,
        predictions: assessment.threatPredictions?.map((tp) => ({
          threatType: tp.threatType,
          probability: tp.probability,
          impact: tp.impact,
          estimatedTimeframe: tp.estimatedTimeframe,
          confidence: tp.confidence,
        })),
        updatedAt: new Date(),
      };

      const updatedFields: Partial<IncidentEntity> = {
        metadata: {
          ...currentMetadata,
          riskAssessment: riskPayload,
        },
      };

      // Appends execution record to agentHistory and persists updates
      const updatedIncident = await this.sharedMemory.write(incidentId, "risk-evaluator", {
        status: "success",
        confidence: assessment.confidence,
        reasoning: assessment.reasoning,
        outputData: riskPayload,
        updatedFields,
      });

      return updatedIncident;
    } catch (error: any) {
      throw new SharedMemoryFailureError(
        `Failed to append Risk Assessment to Shared Incident Memory: ${error.message}`,
        error
      );
    }
  }
}
